name: update-hook
on:
  workflow_dispatch:
jobs:
  update-hook:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v5
      - name: Create empty commit and push
        run: |
          git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git pull
          git commit --allow-empty -m "update-$(date +'%Y-%m-%d-%H-%M')"
          git push origin main
